/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentsIndexRouteImport } from './routes/contents.index'
import { Route as ContentsCategoryRouteImport } from './routes/contents.$category'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsIndexRoute = ContentsIndexRouteImport.update({
  id: '/contents/',
  path: '/contents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsCategoryRoute = ContentsCategoryRouteImport.update({
  id: '/contents/$category',
  path: '/contents/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/visit': typeof VisitRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/contents/$category': typeof ContentsCategoryRoute
  '/contents/': typeof ContentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/visit': typeof VisitRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/contents/$category': typeof ContentsCategoryRoute
  '/contents': typeof ContentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/visit': typeof VisitRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/contents/$category': typeof ContentsCategoryRoute
  '/contents/': typeof ContentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/visit'
    | '/why-choose-us'
    | '/contents/$category'
    | '/contents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/visit'
    | '/why-choose-us'
    | '/contents/$category'
    | '/contents'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/visit'
    | '/why-choose-us'
    | '/contents/$category'
    | '/contents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  VisitRoute: typeof VisitRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  ContentsCategoryRoute: typeof ContentsCategoryRoute
  ContentsIndexRoute: typeof ContentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents/': {
      id: '/contents/'
      path: '/contents'
      fullPath: '/contents/'
      preLoaderRoute: typeof ContentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents/$category': {
      id: '/contents/$category'
      path: '/contents/$category'
      fullPath: '/contents/$category'
      preLoaderRoute: typeof ContentsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  VisitRoute: VisitRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  ContentsCategoryRoute: ContentsCategoryRoute,
  ContentsIndexRoute: ContentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
